/**
 * Open team / staff roles at EzyHelpers, ported from the live careers pages
 * (www.ezyhelpers.com/careers/*). Copy is taken from the live postings —
 * do not invent salaries, benefits, or claims when editing.
 */

export type CareerCategory =
  | "Care roles"
  | "City leadership"
  | "Operations"
  | "Growth & Marketing"
  | "Tech & Product"
  | "Founder's Office";

export interface CareerRole {
  slug: string;
  title: string;
  /** Display location as shown on the live posting. */
  location: string;
  /** City used for JobPosting structured data. */
  city: string;
  /** Display employment type (chip text). */
  type: string;
  /** schema.org employmentType value. */
  employmentType: "FULL_TIME" | "INTERN";
  category: CareerCategory;
  /** ISO date shown as "Posted …" on the live page; omitted when the page shows none. */
  datePosted?: string;
  summary: string;
  responsibilities: string[];
  requirements: string[];
}

/** Display order for the grouped "Open roles" section. */
export const CAREER_CATEGORIES: CareerCategory[] = [
  "Care roles",
  "City leadership",
  "Operations",
  "Growth & Marketing",
  "Tech & Product",
  "Founder's Office",
];

export const CAREER_ROLES: CareerRole[] = [
  {
    slug: "chief-of-staff-intern",
    title: "Chief of Staff Intern",
    location: "Bangalore (hybrid)",
    city: "Bangalore",
    type: "Internship (3 months)",
    employmentType: "INTERN",
    category: "Founder's Office",
    summary:
      "Three months, high intensity, real responsibility in the Founder’s Office — operations, data, and founder projects with a credible path to a full-time role.",
    responsibilities: [
      "Fix broken processes across sales, sourcing, and operations",
      "Build dashboards for helpers, placements, conversions, and replacements",
      "Work directly with founders on prioritisation and key decisions",
      "Own projects end to end — no handoff culture",
      "Spot bottlenecks, propose fixes, and ship",
    ],
    requirements: [
      "You enjoy messy, ambiguous problems",
      "You take ownership without being asked",
      "You can move forward with incomplete information",
      "You have built or tried to build something — even small",
    ],
  },
  {
    slug: "ai-first-associate-product-manager",
    title: "AI-First Associate Product Manager (APM)",
    location: "Bangalore (HSR Layout)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Tech & Product",
    datePosted: "2026-04-07",
    summary:
      "Own the execution engine for our tech and AI layer: turn Sales, Sourcing, and Ops problems into shipped automations, tools, and dashboards — with a full task pipeline and founder access.",
    responsibilities: [
      "Work with Sales, Sourcing, Operations, and founders to spot repetitive workflows, inefficiencies, and gaps; turn them into AI automations, internal tools, dashboards, and process fixes.",
      "Own the task pipeline end to end: maintain a continuous queue of work, break ideas into simple PRDs and small executable tasks, and prioritise by business impact, speed to deploy, and revenue or efficiency gain.",
      "Partner with developers and leverage no-code and AI tools (e.g. Lovable, GPT workflows) for fast build cycles; write clear specs, understand system logic, and test outputs rigorously — deep coding is not required.",
      "Own production and deployment: move features from idea through dev, testing, and release; keep release tracking, version notes, and bug visibility so you are the last-mile owner of execution.",
      "Build and evolve dashboards for sales performance, sourcing efficiency, placement and replacement metrics; use Supabase and internal systems to turn raw data into decisions.",
      "Run feedback loops with sales, field officers, and customers; continuously improve helper onboarding and the customer placement journey.",
      "Implement AI and automation where it matters: e.g. call summaries, WhatsApp flows, smarter matching, auto MIS — always tied to measurable ops outcomes.",
    ],
    requirements: [
      "Roughly 1–3 years in a product, ops-tech, or high-ownership role; mindset and execution matter more than exact tenure.",
      "Strong problem-solving and ability to break complex workflows into shippable slices.",
      "High ownership: you push work across the line, not only document it.",
      "Solid product thinking — structured written specs, clear acceptance criteria, and judgment on trade-offs.",
    ],
  },
  {
    slug: "junior-software-developer-bangalore",
    title: "Junior Software Developer",
    location: "Bengaluru",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Tech & Product",
    datePosted: "2026-06-02",
    summary:
      "Build and ship features on CHAP, our internal CRM, with Python and Django. A high-ownership role for someone eager to learn, with direct mentorship and a clear path to Mid-Level Software Engineer.",
    responsibilities: [
      "Build and improve customer, helper, and job management modules within our Django-based CRM platform.",
      "Develop new features and maintain existing application code using Python and Django.",
      "Integrate third-party services including payment gateways and communication APIs (e.g. WhatsApp, SMS).",
      "Create internal reports, dashboards, and business workflow automation tools.",
      "Debug and resolve issues in production applications in a timely and reliable manner.",
      "Collaborate with senior developers through code reviews and pair programming sessions.",
      "Write clean, maintainable code with appropriate documentation and test coverage.",
    ],
    requirements: [
      "0–2 years of professional or project-based experience in Python development.",
      "Basic understanding of Django or a comparable web framework.",
      "Working knowledge of SQL and relational databases (PostgreSQL preferred).",
      "Familiarity with HTML, CSS, JavaScript and an understanding of how web applications work.",
      "Strong problem-solving instincts and a genuine willingness to learn on the job.",
      "Basic familiarity with Docker and containerised development environments.",
      "Ability to communicate clearly with teammates and ask good questions.",
    ],
  },
  {
    slug: "sales-executive-bangalore",
    title: "Sales Executive",
    location: "Bangalore (HSR Layout · on-site)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Growth & Marketing",
    datePosted: "2026-03-16",
    summary:
      "Convert family inquiries into registrations and placements: inbound and outbound calls, clear explanations of how EzyHelpers works, disciplined CRM hygiene, and teamwork with sourcing and ops.",
    responsibilities: [
      "Handle inbound and outbound sales calls with customers seeking domestic help; qualify budget, role type, timing, location, and household preferences.",
      "Explain EzyHelpers' service model, verification approach, process steps, plans, and charges clearly — no jargon, no pressure tactics.",
      "Guide interested customers through registration, payment or confirmation steps, and next milestones with calm professionalism.",
      "Follow up persistently on warm leads (calls, WhatsApp where appropriate) until closure or a clean disqualification — with notes every time.",
      "Maintain accurate lead data, call outcomes, and pipeline stages in CRM, spreadsheets, or internal tools your manager defines.",
      "Coordinate with sourcing and operations so customer promises in sales match what the field team can fulfil; flag mismatches early.",
      "Handle common objections (price, trust, timelines) with empathy; escalate edge cases to your lead when needed.",
      "Track personal and team targets (calls, registrations, confirmations, revenue contribution) and participate in daily or weekly sales huddles.",
      "Support repeat enquiries, renewals, or upsell paths where the playbook applies.",
    ],
    requirements: [
      "Strong spoken communication and persuasion — confident, respectful, never pushy.",
      "Ability to conduct sales conversations in English, Hindi, and Kannada (customers switch languages often).",
      "Solid listening skills: you can restate a family's problem before you pitch.",
      "Disciplined follow-up habits; you treat “no answer yet” as a state to manage, not ignore.",
      "Comfort in a target-driven environment (individual and team KPIs).",
      "Basic hands-on comfort with CRM tools, Google Sheets / Excel, or similar — we will train you on our stack.",
      "Currently based in Bangalore (or able to relocate and work daily from our HSR Layout office).",
    ],
  },
  {
    slug: "field-officer-bangalore",
    title: "Field Officer",
    location: "Bangalore (field travel · HSR office base)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Operations",
    datePosted: "2026-04-08",
    summary:
      "On-ground verification, quality checks, and helper touchpoints across Bangalore — you make our “verified help” promise real before a family ever books.",
    responsibilities: [
      "Conduct field visits and in-person verification steps for helpers (identity, address, references, and other checks defined in our SOPs).",
      "Run structured interviews or screening conversations; assess fit, experience, and documentation; record outcomes clearly in CRM / internal apps the same day.",
      "Capture photos, documents, and notes per policy; ensure files are complete and legible for audit and quality review.",
      "Support helper onboarding touchpoints — briefings on expectations, app usage where applicable, and next steps after verification.",
      "Perform quality audits, spot checks, or re-verifications when ops or leadership flags risk or repeat issues.",
      "Coordinate with sourcing and city ops on schedules, priorities, and escalations; communicate delays or blockers early.",
      "Represent EzyHelpers professionally with helpers and, when required, with families for in-person fit or clarification visits (as per playbook).",
      "Follow safety guidelines for solo field work; use check-ins and reporting lines as defined by the company.",
      "Maintain daily activity logs (visits, outcomes, mileage or time) so dashboards and SLAs stay accurate.",
    ],
    requirements: [
      "Comfort with full-time field work across Bangalore — different neighbourhoods, traffic, and schedules.",
      "Valid two-wheeler license and own vehicle preferred; ability to travel independently for most of the workday.",
      "Strong smartphone skills: mobile apps, WhatsApp, maps, and uploading photos or forms without friction.",
      "Clear communication in English and Hindi; Kannada is important for many local conversations — you should be able to hold basic professional dialogues in all three where needed.",
      "High integrity and discretion when handling IDs, addresses, and personal data.",
      "Reliable documentation habits — if it is not logged, it did not happen.",
      "Respect for domestic workers; firm on standards without being dismissive or rude.",
    ],
  },
  {
    slug: "sourcing-lead-bangalore",
    title: "Sourcing Lead (Field + Tele)",
    location: "Bangalore (HSR office · field + floor)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Operations",
    datePosted: "2026-04-09",
    summary:
      "Own EzyHelpers’ supply engine: Field Officers on the ground and tele-sourcing callers — consistent helper inflow, strong profiles, fast path to placement, tight coordination with sales.",
    responsibilities: [
      "Own end-to-end supply: lead → call → profile → verify → ready → placement; ensure daily visibility of pipeline and bottlenecks.",
      "Maintain availability of helpers across live-in, full-time, part-time, and on-demand; balance category mix with sales demand.",
      "Lead Field Officers: territories, daily visit targets, sourcing tactics by area; track visits, leads generated, profiles created, and productivity.",
      "Enforce field discipline: app check-in/check-out, live tracking where used, daily work reporting (DWR), and escalation when standards slip.",
      "Manage tele-sourcing: call volumes, connect rates, lead-to-profile conversion, follow-up rigour; allocate leads fairly and track performance.",
      "Build and refine systems for lead allocation, call logging, and performance monitoring (CRM, sheets, internal tools).",
      "Own profile quality: complete, accurate, role-aligned records to cut wrong matches, customer rejections, and unnecessary replacements.",
      "Ensure verification and compliance pathways are followed: Aadhaar, background checks, police verification where applicable; keep the supply pool audit-ready.",
      "Partner with sales on fast matching, placement success, time to closure, and profile-to-placement ratio; surface supply gaps before they hit revenue.",
      "Spot skill and expectation gaps; coordinate basic training or readiness steps so helpers are job-ready, salary-aligned, and expectation-aligned.",
      "Track field metrics (leads and profiles per FO, cost per helper), tele metrics (calls, connects, conversions), and overall pool health (active helpers, placement conversion, replacement rate, time to closure).",
      "Write and improve SOPs for field sourcing, tele sourcing, and profiling; push speed, quality, and efficiency without cutting corners.",
    ],
    requirements: [
      "Roughly 3–6 years in blue-collar hiring, staffing, recruitment, or high-volume supply ops — with hands-on experience managing both field teams and tele-calling teams.",
      "Proven people leadership: coaching, targets, attendance and output control for on-ground and phone-based teams.",
      "Target-driven execution: you plan in weekly and daily horizons, not only in decks.",
      "Comfort with data: dashboards, conversion funnels, and using numbers to reallocate effort.",
      "Strong systems for follow-up, quality checks, and accountability — you cannot stand chaos without fixing it.",
      "High ownership in ambiguous, high-pressure environments; solution-oriented when volume spikes or demand shifts.",
      "Based in Bangalore (or able to relocate); able to be present with field and floor teams as needed from HSR Layout.",
      "Professional communication in English and Hindi; Kannada is a strong plus for local helper and partner conversations.",
    ],
  },
  {
    slug: "supply-sourcing-executive-bangalore",
    title: "Supply Sourcing Executive",
    location: "Bangalore (HSR Layout · on-site)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Operations",
    datePosted: "2026-04-15",
    summary:
      "Tele-sourcing engine for verified helpers: outbound and inbound calls, complete profiles, disciplined CRM and follow-ups, and tight handoffs to field verification — you keep supply moving so sales can place with confidence.",
    responsibilities: [
      "Run outbound and inbound tele-sourcing campaigns to recruit helpers and job-seekers across categories (live-in, full-time, part-time, on-demand) using lead lists, referrals, and inbound callbacks as assigned.",
      "Conduct structured phone screening: experience, role fit, salary expectations, location and timing, family constraints, and basic eligibility; capture outcomes clearly in CRM or internal tools the same day.",
      "Build complete, accurate helper profiles — skills, work history, references where applicable, availability, and category — so matching and field verification are not reworked later.",
      "Drive follow-up discipline: callbacks, document collection reminders, no-show recovery, and status updates until a lead is profiled, disqualified for a clear reason, or handed to field with a clean brief.",
      "Maintain CRM / sheet hygiene: call logs, dispositions, next actions, and pipeline stages so dashboards, targets, and lead allocation stay truthful.",
      "Coordinate with Field Officers and sourcing leadership on visit scheduling, priority geographies, and edge cases (documentation gaps, salary misalignment, risk flags).",
      "Hit and track personal metrics: dials, meaningful connects, profiles created or advanced, verification handoffs, and conversion ratios defined by your manager.",
      "Represent EzyHelpers professionally on every call — respectful tone with workers, no false promises on earnings or placements, and adherence to consent and data-handling norms.",
      "Participate in daily or weekly huddles; share learnings on what messaging or lead sources convert; suggest improvements to scripts, lists, or process within the playbook.",
    ],
    requirements: [
      "Strong spoken communication for high-volume phone work — clear, patient, and confident without sounding scripted or pushy.",
      "Ability to hold professional conversations in English and Hindi; Kannada is important for many helper-side conversations in Bangalore.",
      "Prior experience in tele-calling, recruitment calling, BPO/KPO outbound, inside sales, or high-volume customer/supplier outreach (roughly 6 months–3 years is typical; judgment and output matter more than exact tenure).",
      "Comfort with targets and activity metrics (calls, connects, conversions) and honest self-reporting.",
      "Basic digital literacy: CRM, spreadsheets, WhatsApp coordination, and typing notes while on calls or immediately after.",
      "High ownership of your pipeline — you treat “no answer” and “call back Tuesday” as states to manage, not forget.",
      "Full-time availability from our Bangalore office (HSR Layout); this is not a remote role.",
    ],
  },
  {
    slug: "city-head-ghaziabad",
    title: "City Head – Ghaziabad",
    location: "Ghaziabad",
    city: "Ghaziabad",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "City leadership",
    datePosted: "2026-04-10",
    summary:
      "Own end-to-end business performance in Ghaziabad: P&L, demand and supply, operations, and local growth — building a high-efficiency, profitable city.",
    responsibilities: [
      "Own city P&L: placements, revenue, margins, and cost efficiency; improve unit economics over time.",
      "Generate consistent demand through society tie-ups, referrals, local marketing, and disciplined sales conversion.",
      "Ensure helper availability: sourcing channels, field officers, and a healthy supply–demand balance.",
      "Run operations for a fast placement cycle with fewer escalations and delays; protect customer experience.",
      "Lead the local team across sales, sourcing, and field; set targets, track performance, and drive accountability.",
      "Uphold verification, documentation, and process compliance; keep system records accurate and audit-ready.",
      "Build partnerships with societies, agents, and local networks to expand presence across Ghaziabad.",
    ],
    requirements: [
      "Graduate.",
      "Roughly 3–6 years in sales, operations, or business roles with ownership of outcomes and targets.",
      "Proven ability to lead small teams and manage execution, not only planning.",
      "Strong problem-solving mindset and comfort with ambiguity in a growing market.",
      "Based in or able to work full-time from Ghaziabad.",
    ],
  },
  {
    slug: "city-head-chennai",
    title: "City Head – Chennai",
    location: "Chennai",
    city: "Chennai",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "City leadership",
    datePosted: "2026-04-10",
    summary:
      "Launch and scale Chennai: full P&L, supply and demand, operations, and team performance — from early growth to a stable, profitable market.",
    responsibilities: [
      "Own city revenue and profitability; drive placements, margins, and operational efficiency.",
      "Build demand through local marketing, apartment and society tie-ups, and referral networks with strong conversion discipline.",
      "Build supply pipelines (agents, field networks) and ensure availability of verified, profile-ready helpers.",
      "Run the placement lifecycle end to end: requirement → matching → placement → support; improve closure speed and satisfaction.",
      "Hire, coach, and manage sales, sourcing, and field teams with clear daily accountability.",
      "Ensure verification and documentation SOPs are followed and CHAP / internal systems stay clean.",
      "Drive local partnerships and brand trust so EzyHelpers is a preferred name for domestic help in Chennai.",
    ],
    requirements: [
      "Graduate; MBA is a plus.",
      "Roughly 3–7 years combining sales and operations execution, ideally with team management.",
      "Understanding of local market dynamics and ability to execute on the ground.",
      "Leadership skills: clarity, follow-through, and performance culture.",
      "Based in or able to relocate to Chennai full-time.",
    ],
  },
  {
    slug: "city-head-hyderabad",
    title: "City Head – Hyderabad",
    location: "Hyderabad",
    city: "Hyderabad",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "City leadership",
    datePosted: "2026-04-10",
    summary:
      "Act as the CEO of the Hyderabad city unit: P&L, revenue growth, supply–demand balance, operations, and team performance in a high-ownership role.",
    responsibilities: [
      "Own monthly targets on placements, revenue, and contribution margins; optimise unit economics (e.g. CAC, cost per placement).",
      "Scale demand: digital and local partnerships, society activations, referrals; manage lead → conversion funnel with central marketing alignment.",
      "Own helper acquisition: sourcing team and field officers, agent and referral networks, healthy supply–demand ratio.",
      "Drive operations excellence across requirement → sourcing → onboarding → placement → post-placement; reduce TAT, replacements, and escalations.",
      "Hire, train, and manage sales, sourcing, and field teams with high accountability and daily performance tracking.",
      "Enforce verification and compliance (e.g. Aadhaar, e-court where applicable), documentation completeness, and disciplined CHAP updates.",
      "Expand via societies, RWAs, agents, and influencers; identify micro-markets for growth within Hyderabad.",
    ],
    requirements: [
      "Graduate; MBA preferred but not mandatory.",
      "Roughly 3–7 years across operations, sales, and/or business management with mandatory experience managing teams and targets.",
      "Strong grasp of P&L and business metrics; data-informed decision making.",
      "High ownership, problem-solving, and ability to thrive in ambiguity.",
      "Based in or able to relocate to Hyderabad full-time.",
    ],
  },
  {
    slug: "city-head-delhi",
    title: "City Head – Delhi",
    location: "Delhi",
    city: "Delhi",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "City leadership",
    datePosted: "2026-04-10",
    summary:
      "Lead one of EzyHelpers’ highest-potential markets: P&L, aggressive growth, operations, and expansion across Delhi.",
    responsibilities: [
      "Drive aggressive growth and city-level P&L: revenue, margins, and profitability.",
      "Scale high-quality leads through digital, partnerships, and on-ground activations; lift conversion consistently.",
      "Build sourcing pipelines and ensure strong availability of verified helpers.",
      "Run seamless placement journeys: reduce turnaround time and escalations.",
      "Build and manage a high-performance local team with clear accountability.",
      "Develop partnerships with premium societies and networks; strengthen referral flywheels.",
    ],
    requirements: [
      "Graduate; MBA preferred.",
      "Roughly 4–8 years in sales, operations, or general management with leadership experience.",
      "Strong execution bias and comfort owning targets end to end.",
      "Data-driven decision making on funnel, unit economics, and supply health.",
      "Based in or able to work full-time from Delhi.",
    ],
  },
  {
    slug: "city-head-bareilly",
    title: "City Head – Bareilly",
    location: "Bareilly",
    city: "Bareilly",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "City leadership",
    datePosted: "2026-04-10",
    summary:
      "Mini-CEO for Bareilly: own revenue, cost, profitability, supply, demand, field execution, and team performance end to end.",
    responsibilities: [
      "Own revenue, cost, and profitability; hit monthly placement and margin targets; improve unit economics.",
      "Build and manage local lead channels; convert inbound, society partnerships, and marketing into closed business.",
      "Ensure consistent quality helper supply; manage sourcing and field officers; maintain supply–demand balance.",
      "Optimise requirement → onboarding → placement flow; minimise escalations and improve satisfaction.",
      "Hire, train, and manage sales, sourcing, and field teams with daily performance tracking.",
      "Ensure verification and documentation completeness; maintain CHAP hygiene.",
      "Expand via apartments, agents, and local partners with a clear city growth plan.",
    ],
    requirements: [
      "Graduate; MBA preferred.",
      "Roughly 3–7 years in operations, sales, or business roles with team and target ownership.",
      "Business acumen and comfort with P&L-style thinking.",
      "Problem-solving mindset and high ownership.",
      "Based in or able to work full-time from Bareilly.",
    ],
  },
  {
    slug: "junior-hr-executive-bangalore",
    title: "Junior HR Executive",
    location: "Bangalore (HSR Layout · office)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Operations",
    datePosted: "2026-04-10",
    summary:
      "Operational HR at the intersection of helper onboarding, verification, internal hiring support, MIS, and coordination with sales, sourcing, and field — backbone of our workforce.",
    responsibilities: [
      "Own helper onboarding and documentation: Aadhaar and checks per process, complete files, accurate CHAP records; align with sourcing and field for profile readiness.",
      "Support internal recruitment: scheduling, candidate coordination, pipeline tracking, and fast hiring TAT for roles such as sales executives and field officers.",
      "Maintain HR operations and MIS: joiners, active employees, attrition, attendance and leaves; weekly and monthly reporting.",
      "Track employee and helper lifecycle: induction, issues, replacements, and churn signals.",
      "Support compliance with verification standards and HR policies; keep audit-ready records.",
      "Coordinate daily with sales (requirements), sourcing (pipeline), and field officers (ground validation) to remove handoff delays.",
      "Support engagement initiatives, employee queries, and a respectful, high-discipline culture.",
    ],
    requirements: [
      "Graduate in any discipline; HR, BBA, or MBA is a plus.",
      "0–2 years experience; freshers with strong execution and follow-through are welcome.",
      "Strong communication in Hindi and basic English; Kannada is a plus.",
      "High ownership, accountability, and coordination skills; comfortable with pace and multitasking.",
      "Daily reporting discipline and responsiveness.",
      "Full-time, work from office in Bangalore (HSR Layout).",
    ],
  },
  {
    slug: "elder-care-attendant-bangalore",
    title: "Elder Care Attendant",
    location: "Bangalore (across the city · within 10 km of your address)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Care for an aging parent in their own home — companionship, daily living, gentle dignity. 60-hour paid training, 24×7 care-manager support, and a real path to higher-paying live-in or specialist roles.",
    responsibilities: [
      "Personal hygiene assistance — bathing, grooming, oral and nail care.",
      "Help with dressing and changing, with dignity always first.",
      "Meal preparation per the patient's dietary plan and feeding when needed.",
      "Medication reminders at the right times, logged in our app.",
      "Vitals tracking — blood pressure, sugar, temperature, oxygen saturation.",
      "Mobility support and fall-prevention checks throughout the day.",
      "Companionship — conversation, walks, reading aloud, light music.",
      "Light housekeeping inside the patient's room (not the whole house).",
      "Daily updates to family on WhatsApp at the end of each shift.",
      "Escalate any health change, however small, to the care manager.",
      "Maintain a clean appearance and wear the EzyHelpers uniform on duty; carry your ID badge at all times.",
    ],
    requirements: [
      "10th standard pass (or equivalent).",
      "Spoken comfort in at least one of: Kannada, Tamil, Telugu, Malayalam, Hindi, English.",
      "Aadhaar card and one address proof.",
      "Two references we can call.",
      "Physical fitness — able to support a patient with mobility.",
      "Patience with elderly people, especially those with memory loss.",
    ],
  },
  {
    slug: "patient-care-attendant-bangalore",
    title: "Patient Care Attendant",
    location: "Bangalore (placements often align with discharging hospital location)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Bring hospital-grade attentiveness home — for recovery, chronic illness, and post-discharge. 80-hour training with supervised hospital exposure, ₹18–30k/month, and a sponsored bridge to formal home-nursing qualification.",
    responsibilities: [
      "Track vitals — BP, sugar, temperature, SpO₂ — and log them in the app.",
      "Feed orally, or assist with NG/RT feeding under nurse supervision.",
      "Observe surgical sites and wound areas; report any change immediately.",
      "Catheter care and incontinence management with dignity.",
      "Reposition bedridden patients every 2–3 hours to prevent pressure sores.",
      "Mobility coaching — bed to chair, chair to walker, supervised walks.",
      "Coordinate with the family's physiotherapist when they visit.",
      "Medication adherence with timing logs.",
      "Hydration and nutrition tracking, including intake/output for some patients.",
      "Daily care reports shared with family and treating doctor (with consent).",
      "Escalate immediately on warning signs — fever, breathlessness, swelling, confusion.",
      "Maintain infection-control practices: hand hygiene, glove use, linen change.",
    ],
    requirements: [
      "12th standard pass, or equivalent.",
      "Some healthcare exposure — hospital attendant, ANM dropout, GDA course, etc.",
      "Comfort reading basic medication labels in English.",
      "Spoken comfort in two of: Kannada, Tamil, Telugu, Hindi, English.",
      "Physical fitness to lift or assist a patient with mobility.",
      "Two professional references.",
    ],
  },
  {
    slug: "live-in-caregiver-bangalore",
    title: "Live-in Caregiver",
    location: "Bangalore (placement matched to your area and the patient’s need)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Stay with one family. Provide round-the-clock presence. Earn more, grow deeper roots. Higher base than day-shift, free boarding, weekly off with a trained relief caregiver, and group accident + term life insurance.",
    responsibilities: [
      "Provide continuous day and night care for one patient.",
      "Personal care, meals, hygiene, mobility, and medication adherence.",
      "Vitals tracking and reporting via the EzyHelpers app.",
      "Repositioning every 2–3 hours if patient is bedridden.",
      "Night-time vigilance with short, scheduled rest cycles.",
      "Light housekeeping in the patient's room (not the whole home).",
      "Family liaison — daily updates, weekly summaries.",
      "Coordinate with visiting physiotherapist, nurse, or doctor.",
      "Maintain a clean appearance and follow the household's quiet hours.",
      "Train the family on the safe handling protocol on day one.",
      "Stay within the agreed scope — no babysitting other family members, no cooking for the wider family.",
      "Honor a minimum 30-day notice if you wish to exit the placement.",
    ],
    requirements: [
      "Minimum 6 months of caregiver experience (with us or elsewhere).",
      "Willingness to live in the family's home for the placement duration.",
      "Comfort with night-time alertness and short-rest cycles.",
      "10th standard or above.",
      "Police verification and Aadhaar verification (we coordinate).",
      "Available for a minimum 3-month commitment per placement.",
    ],
  },
  {
    slug: "dementia-care-specialist-bangalore",
    title: "Dementia Care Specialist",
    location: "Bangalore (match-prioritised for language and household culture)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Specialised caregiver for dementia and Alzheimer’s patients. Continuity, validation, kindness. 120-hour paid training, smaller caseload, longer placements, and higher pay.",
    responsibilities: [
      "Use validation therapy — meet the patient where they are, don't correct facts.",
      "Apply redirection techniques during agitation (change room / activity / topic).",
      "Hold a strict daily routine, with the same timing every day.",
      "Manage sundowning with morning sunlight and low-stimulation evenings.",
      "Wandering prevention — environmental safety, gentle observation, never restraint.",
      "Personal hygiene with dignity-first prompts (avoid shame triggers).",
      "Feeding with swallowing awareness in advanced cases.",
      "Cognitive stimulation: old photos, simple folding, familiar music.",
      "Family coaching — what to say, what not to say, why episodes happen.",
      "Detailed daily logs of sleep, mood, agitation episodes, eating, medications.",
      "Bi-weekly review with our care manager + neurologist input where relevant.",
      "Never raise your voice; never argue; never restrain physically or chemically.",
    ],
    requirements: [
      "At least 12 months of caregiver experience.",
      "Exceptional patience — willingness to answer the same question 20 times warmly.",
      "Completion of our 120-hour dementia training (provided, paid).",
      "Comfort with disturbed sleep schedules (sundowning, night wakings).",
      "Stable temperament — no shouting, no arguing back, no shaming.",
      "Strong references from previous placements.",
    ],
  },
  {
    slug: "home-nursing-assistant-bangalore",
    title: "Home Nursing Assistant",
    location: "Bangalore-wide (visits clustered geographically to minimise riding time)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Clinical home-visit role — IV, dressings, catheter changes — for the medical edge cases. ANM/GNM with a Karnataka State Nursing Council registration. ₹25–45k/month including per-visit pay and fuel allowance.",
    responsibilities: [
      "Administer scheduled IV fluids and IV medication per doctor's prescription.",
      "Give intramuscular and subcutaneous injections.",
      "Perform wound dressings and post-surgical site care.",
      "Catheter insertion, change, and care.",
      "Manage Ryle's tube / NG-feed insertion and replacement.",
      "Tracheostomy care (basic) and suction.",
      "Take detailed vitals and document changes.",
      "Coordinate with the patient's care attendant on the daily plan.",
      "Share signed visit notes with family and treating doctor.",
      "Stock and maintain your visit kit; restock from our office monthly.",
      "Maintain infection-control protocols on every visit.",
      "Escalate any change in patient status to the clinical care manager immediately.",
    ],
    requirements: [
      "ANM (Auxiliary Nurse Midwife) or GNM (General Nursing and Midwifery) diploma.",
      "Registered with the Karnataka State Nursing Council.",
      "Minimum 2 years clinical experience (hospital or home setting).",
      "Comfort with IV cannulation and IV medication.",
      "English + at least one Indian language.",
      "Two-wheeler license and willingness to ride for visits.",
      "Smartphone with internet access.",
    ],
  },
  {
    slug: "care-supervisor-bangalore",
    title: "Care Supervisor",
    location: "Bangalore (assigned zone — East, West, South, North, or Central)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Field supervisor visiting 15–20 placements bi-weekly to keep care quality high. Salaried role for an experienced caregiver or home nurse ready to step off direct patient care — ₹35–55k/month + fuel allowance.",
    responsibilities: [
      "Visit 15–20 active care placements every two weeks across your assigned zone.",
      "Sit with the patient and family for 30–45 minutes per visit.",
      "Review the caregiver's daily log book and app entries.",
      "Observe the room, the patient's appearance, and the household tone.",
      "Re-train the caregiver on the spot if you see protocol gaps.",
      "Document findings — strengths, gaps, escalations — in our supervisor report.",
      "Identify caregivers at risk of burnout and rotate them out kindly.",
      "Be the family's first escalation channel for non-clinical concerns.",
      "Help onboard new caregivers into their first placement.",
      "Run monthly small-group meetings with caregivers in your zone.",
      "Flag any safeguarding concern immediately to the Operations Head.",
      "Maintain a clean professional appearance and never miss a scheduled visit without notice.",
    ],
    requirements: [
      "GNM diploma or BSc Nursing, or 5+ years caregiving experience with strong references.",
      "3+ years in patient care or supervisory role.",
      "Two-wheeler license and ability to ride safely across Bangalore.",
      "Spoken comfort in Kannada + Hindi + English (Tamil/Telugu a bonus).",
      "Smartphone literacy for visit logging and family WhatsApp groups.",
      "Emotional maturity — ability to deliver hard feedback gently.",
    ],
  },
  {
    slug: "care-manager-operations-bangalore",
    title: "Care Manager (24×7 Operations)",
    location: "Bangalore (EzyHelpers office, Indiranagar)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Central operations role — the person families and caregivers call when something matters. Rotating shifts including nights; ₹40–70k/month with night-shift differential, cab transport, and a real path to Operations Head.",
    responsibilities: [
      "Pick up every inbound call, message, and WhatsApp within the response SLA.",
      "Triage emergencies — connect to ambulance partner, treating doctor, family.",
      "Dispatch caregivers for same-day placements (within 6-hour SLA).",
      "Handle replacement requests within 24 hours.",
      "Maintain the duty log — every call, every action, every outcome.",
      "Coordinate hospital discharge placements with case managers.",
      "Brief incoming caregivers on each new family before they leave.",
      "Be the family's day-to-day point of contact for any concern.",
      "Escalate clinical questions to the Clinical Care Manager.",
      "Handle billing queries and payment follow-ups.",
      "Run the monthly retention call with active long-term clients.",
      "Document everything — we are an evidence-driven operation.",
    ],
    requirements: [
      "Bachelor's degree (any discipline).",
      "Excellent spoken Kannada + Hindi + English.",
      "2+ years in customer-facing operations (hospital, hotel, startup ops, etc.).",
      "Comfort with shift work, including night shifts on rotation.",
      "Strong written communication for WhatsApp and email.",
      "Calm under pressure — references should call out your composure.",
      "Comfortable with software tools (we use a custom dispatch app).",
    ],
  },
  {
    slug: "care-coordinator-home-healthcare-bangalore",
    title: "Care Coordinator – Home Healthcare",
    location: "Bangalore (HSR Layout · office-based)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-06-03",
    summary:
      "Office-based coordination role at the heart of our home healthcare service: understand family needs, match the right caregiver or nurse, and ensure reliable, continuous care delivery. 2–3 years in healthcare or caregiving, 6 days a week in HSR Layout.",
    responsibilities: [
      "Speak with families to understand care requirements in detail — elderly, post-operative, palliative, bedridden, dementia, physiotherapy support, general caregiving, or nursing support.",
      "Ask the right questions to assess the patient's condition, mobility level, medical dependency, food habits, language preference, duty timings, and family expectations; document everything in the internal tracker.",
      "Coordinate with staff nurses, nursing assistants, GDA/ANM/GNM candidates, physiotherapists, and caregivers; check availability, experience, location, language skills, and suitability.",
      "Match the right caregiver or healthcare support staff to client needs, and brief them on patient condition, family expectations, hygiene standards, duty timings, and responsibilities before assignment.",
      "Manage day-to-day coordination between clients, caregivers, nurses, physiotherapists, and internal teams; follow up after placement to ensure satisfaction.",
      "Resolve issues around caregiver behaviour, attendance, duty understanding, replacements, or service gaps; arrange replacements and ensure continuity of care without disruption.",
      "Help families choose the right level of care based on the patient's condition, and escalate medical or clinical concerns to qualified professionals when needed.",
      "Screen and profile caregivers, nursing assistants, staff nurses, and physiotherapists by skills, past cases, language, location, salary expectation, shift preference, and availability; maintain an updated staff database.",
      "Maintain polite, clear, professional communication with families; give realistic updates without overpromising and handle concerns with empathy and ownership.",
      "Coordinate with the sales and operations team for closures and service delivery.",
      "Maintain accurate records of requirements, staff profiles, placements, follow-ups, complaints, replacements, and service status; prepare daily/weekly reports on active cases, pending requirements, staff availability, and escalations.",
    ],
    requirements: [
      "2–3 years of experience in home healthcare operations, elderly/patient care coordination, nursing bureau or caregiver placement, hospital discharge or physiotherapy service coordination, palliative care support, healthcare customer support, or medical/nursing staff coordination.",
      "Good understanding of home healthcare and caregiving services and the ability to understand patient and elderly care requirements.",
      "Strong communication in English and Hindi; Kannada is an added advantage.",
      "Ability to coordinate with caregivers, nurses, physiotherapists, and families.",
      "Strong follow-up and documentation skills.",
      "Empathy and patience while handling families and elderly care cases, including sensitive healthcare conversations.",
      "Good judgment in matching the right caregiver to the right family.",
      "Comfortable working from the office 6 days a week.",
      "Basic computer knowledge — Google Sheets, Excel, WhatsApp, CRM, or internal tracking tools.",
    ],
  },
  {
    slug: "caregiver-trainer-bangalore",
    title: "Caregiver Trainer",
    location: "Bangalore (training space, Indiranagar · with field visits across the city)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Care roles",
    datePosted: "2026-05-09",
    summary:
      "Design and deliver the training that makes every EzyHelpers caregiver good at this work. BSc Nursing or GNM, 5+ years experience, instructional chops. ₹50–80k/month + conference budget + equity option.",
    responsibilities: [
      "Run new caregiver cohorts (8–15 trainees, 60 hours over 2.5 weeks).",
      "Run specialist cohorts (dementia, bedridden, post-surgery, female-care).",
      "Deliver classroom modules + role-plays + supervised home practice.",
      "Maintain and version the curriculum — written, illustrated, and on video.",
      "Assess trainees and certify them for placement.",
      "Spend 1–2 days a week in active placements observing real practice.",
      "Identify the gap between curriculum and field reality, close it.",
      "Run quarterly refresher programmes for active caregivers.",
      "Coach caregivers flagged by supervisors as needing support.",
      "Maintain the training space, equipment, mannequins, supplies.",
      "Document training outcomes — completion rates, ratings, drop-offs.",
      "Represent EzyHelpers at hospital and academic training partnerships.",
    ],
    requirements: [
      "BSc Nursing or GNM diploma.",
      "5+ years clinical or caregiver-management experience.",
      "Strong instructional skills — comfortable in front of a 15-person room.",
      "Fluent Kannada + Hindi + English.",
      "Empathy with first-generation learners.",
      "Curriculum design instinct — comfort writing and revising training materials.",
    ],
  },
  {
    slug: "vendor-partner-onboarding-specialist-bangalore",
    title: "Vendor & Partner Onboarding Specialist",
    location: "Bangalore-wide (heavy intra-city travel for vendor site visits)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Operations",
    datePosted: "2026-05-09",
    summary:
      "Sign up and integrate the ambulance, physio, equipment, and clinic partners that round out our care service. Operations-meets-BD role with negotiation authority. ₹40–65k/month + travel allowance.",
    responsibilities: [
      "Source vendors across categories: ambulance, physiotherapy, equipment rental, pharmacy, lab pickup, geriatricians.",
      "Run vendor verification: company registration, GST, insurance, references, on-site visit.",
      "Negotiate commercial terms — pricing, SLAs, exclusivity, billing cadence.",
      "Onboard partner teams on our process — escalation card, response SLAs, billing.",
      "Maintain the partner directory and route requests to the right vendor.",
      "Track partner performance against SLA every week.",
      "Run monthly partner reviews — top performers get more volume; under-performers get warnings.",
      "Handle vendor escalations and family complaints involving vendors.",
      "Maintain commercial paperwork — agreements, renewals, indemnities.",
      "Identify gaps in the partner network and proactively source.",
      "Negotiate volume discounts as we grow.",
      "Document the entire vendor lifecycle in our operations playbook.",
    ],
    requirements: [
      "2+ years vendor management, partnership operations, or B2B account management.",
      "Comfort with commercial negotiation and contract paperwork.",
      "Spoken Kannada + Hindi + English.",
      "Two-wheeler for vendor site visits.",
      "Process discipline — clean documentation, contract version control, SLA tracking.",
      "Polished judgement — you're the company's face to many small businesses.",
      "Comfort using spreadsheets and basic CRM.",
    ],
  },
  {
    slug: "hospital-partnerships-manager-bangalore",
    title: "Hospital Partnerships Manager",
    location: "Bangalore (heavy intra-city travel)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Growth & Marketing",
    datePosted: "2026-05-09",
    summary:
      "Build referral relationships with Bangalore’s major hospitals so patients leave with us already lined up. Healthcare BD with uncapped commission, base ₹60k–1.2L/month + ₹2k–5k per referred placement, and stock options after a year.",
    responsibilities: [
      "Build relationships with 15–20 Bangalore hospitals across 18 months.",
      "Identify the right contacts — case managers, ward heads, geriatricians, surgeons.",
      "Present EzyHelpers credibly: process, training, pricing, escalation, outcomes.",
      "Negotiate discharge pathway integration, flyer placement, ward-level briefings.",
      "Coordinate with Care Managers to ensure smooth hospital-to-home handover.",
      "Maintain a CRM of every hospital contact, conversation, and follow-up.",
      "Run quarterly review meetings with our top 5 hospital partners.",
      "Field hospital escalations — if anything goes wrong in a partnered discharge, you own it.",
      "Identify cross-referral opportunities (geriatricians, physiotherapists, etc.).",
      "Represent EzyHelpers at hospital medical conferences and clinician meet-ups.",
      "Bring market intelligence back — what are other agencies offering hospitals.",
      "Hit a referral-volume target (currently 40 hospital-referred placements / month).",
    ],
    requirements: [
      "Bachelor's degree, MBA preferred.",
      "3+ years healthcare business development, account management, or hospital sales.",
      "Existing relationships in Bangalore healthcare are a strong plus.",
      "Polished spoken English; comfort with clinical conversation.",
      "Strong written proposals and CRM discipline.",
      "Two-wheeler or willingness to travel intra-city daily.",
      "Calm, low-pressure sales style — we don't push, we earn.",
    ],
  },
  {
    slug: "content-brand-lead-bangalore",
    title: "Content & Brand Lead",
    location: "Bangalore (hybrid · 2 days in Indiranagar office, 3 remote)",
    city: "Bangalore",
    type: "Hybrid",
    employmentType: "FULL_TIME",
    category: "Growth & Marketing",
    datePosted: "2026-05-09",
    summary:
      "Own the editorial voice, SEO/AEO, and every word a family reads from us. Healthcare brand editor / senior writer with portfolio. ₹70k–1.5L/month + stock options + conference budget.",
    responsibilities: [
      "Publish 4 long-form journal posts per month, each ≥1,200 words.",
      "Maintain and version-control the entire content corpus (services, localities, journal).",
      "Run editorial review for clinical accuracy with the consulting nurse.",
      "Commission illustration, photography, and short video from agencies.",
      "Manage SEO end-to-end — keyword strategy, on-page optimisation, AEO, llms.txt.",
      "Write the monthly newsletter (~5,000 subscribers, growing).",
      "Maintain brand-voice guide and review all family-facing copy.",
      "Build and brief external freelancers as content needs scale.",
      "Track content performance — rankings, time on page, conversions.",
      "Run quarterly content reviews with the founder.",
      "Represent the brand at small media conversations and partnerships.",
      "Develop the editorial-board partnership with our consulting clinicians.",
    ],
    requirements: [
      "5+ years content / editorial experience, ideally in healthcare or wellness.",
      "Demonstrated long-form writing chops (portfolio required).",
      "Working knowledge of SEO and analytics (Search Console, GA4).",
      "Ability to edit clinical content for a lay audience without losing accuracy.",
      "Strong project management — running 4 pieces a month with research, edit, illustration.",
      "Comfort with markdown, Git, or similar version-controlled workflows.",
    ],
  },
  {
    slug: "family-care-counsellor-sales-bangalore",
    title: "Family Care Counsellor (Inbound Sales)",
    location: "Bangalore (EzyHelpers office, Indiranagar)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Growth & Marketing",
    datePosted: "2026-05-09",
    summary:
      "Talk to anxious families calling us. Help them choose. Convert with empathy, not pressure. Consultative sales — base ₹35–65k/month + variable per closed booking + stock options after a year.",
    responsibilities: [
      "Pick up every inbound family call within the ringing SLA.",
      "Reply to every booking-form lead, WhatsApp enquiry, and email within 30 minutes during business hours.",
      "Listen first — what is the actual situation, who is the patient, what is urgent.",
      "Recommend the right service plan honestly (sometimes that means recommending less, not more).",
      "Quote pricing transparently; explain what's included and what's not.",
      "Coordinate the first match call with the Care Manager when the family is ready.",
      "Schedule and conduct discovery calls for higher-touch enquiries (NRI families, complex cases).",
      "Send a follow-up summary on WhatsApp within 30 minutes of every call.",
      "Maintain meticulous CRM records — every lead, every conversation, every objection.",
      "Identify common objections and feed insights back to Marketing and Content.",
      "Track personal conversion rate, response time, and lead quality every week.",
      "Handle the occasional escalation from a confused or anxious family with patience.",
    ],
    requirements: [
      "3+ years inbound sales, customer success, or consultative selling.",
      "Polished English + fluent Kannada or Hindi.",
      "Empathetic, non-pushy temperament — references should describe you as patient.",
      "CRM discipline (HubSpot, Salesforce, Zoho, or similar).",
      "Comfort quoting prices and handling money conversations.",
      "Composure on emotionally heavy calls.",
      "Strong written communication for WhatsApp follow-ups.",
    ],
  },
  {
    slug: "digital-marketing-strategist-bangalore",
    title: "Digital Marketing Strategist",
    location: "Bangalore (hybrid · 2 days at Indiranagar office, 3 remote)",
    city: "Bangalore",
    type: "Hybrid",
    employmentType: "FULL_TIME",
    category: "Growth & Marketing",
    datePosted: "2026-05-09",
    summary:
      "Own paid acquisition, SEO performance, email, and the analytics that tell us what’s working. 4+ years D2C/healthcare growth. ₹70k–1.3L/month + equity + a modern stack and real budget authority.",
    responsibilities: [
      "Plan and run paid acquisition across Google Ads, Meta, and YouTube.",
      "Set and manage the monthly performance budget (currently ₹4–6L/month, scaling).",
      "Manage SEO performance tracking — rankings, CTR, page experience, technical health.",
      "Own the analytics stack — GA4, Search Console, Looker Studio dashboards.",
      "Build and run lifecycle email campaigns (newsletter, post-booking, re-engagement).",
      "Run continuous landing-page A/B tests on top-converting pages.",
      "Build retargeting and audience strategies (Meta CAPI, Google Customer Match).",
      "Coordinate with Content & Brand on SEO keyword priorities and content gaps.",
      "Coordinate with Family Care Counsellor team on lead quality feedback loops.",
      "Monthly performance review with founder — channels, CAC, payback, retention.",
      "Maintain the marketing tech stack (analytics, CDP, email, attribution).",
      "Identify and pilot new channels — affiliates, WhatsApp marketing, partnerships.",
    ],
    requirements: [
      "4+ years digital marketing / growth at a D2C, healthcare, or consumer-services brand.",
      "Hands-on Google Ads + Meta Ads experience (not just agency-managed).",
      "Strong GA4 and Search Console proficiency.",
      "Demonstrated SEO performance work (rankings → traffic → conversions).",
      "Comfort with A/B testing tools (VWO, Optimizely, Posthog, or similar).",
      "Email lifecycle experience (HubSpot, Mailchimp, Customer.io, or similar).",
      "Strong commercial instinct — every metric tied to revenue and unit economics.",
    ],
  },
  {
    slug: "technical-content-writer-bangalore",
    title: "Technical Content Writer",
    location: "Bangalore (hybrid · 2 days in Indiranagar office, 3 remote)",
    city: "Bangalore",
    type: "Hybrid",
    employmentType: "FULL_TIME",
    category: "Growth & Marketing",
    datePosted: "2026-05-09",
    summary:
      "Write the clinical, condition-specific, and how-to content that powers our most useful pages. Medically accurate, emotionally clear. ₹45–80k/month + book budget + stock options.",
    responsibilities: [
      "Write 2 long-form clinical guides per month (1,500–2,500 words each).",
      "Refresh and expand existing service detail pages quarterly.",
      "Produce condition-specific content (stroke recovery, Parkinson's home care, post-op cardiac, etc.).",
      "Build downloadable checklists and PDFs for families.",
      "Maintain caregiver training manuals and supervisor scripts.",
      "Coordinate clinical review with the consulting nurse on every clinical piece.",
      "Use primary sources (PubMed, WHO, ICMR) — cite responsibly.",
      "Maintain a glossary of caregiving terms for SEO and AEO surfaces.",
      "Internal docs — SOPs for Care Managers, escalation cards for placements.",
      "Collaborate with Content & Brand on long-form journal pieces.",
      "Maintain the version history of clinical content (every claim dated and reviewed).",
      "Localise key content into Kannada and Tamil with translation partners.",
    ],
    requirements: [
      "2+ years technical or healthcare content writing experience.",
      "Portfolio of clinical/medical writing for a lay audience.",
      "Ability to read and translate primary research into plain English.",
      "Strong editing instinct — you'll edit your own work daily.",
      "Comfort with Markdown, version control (Git), or similar workflows.",
      "Familiarity with SEO principles (you'll write H2-friendly, scan-friendly copy).",
    ],
  },
  {
    slug: "field-mobiliser-source-state-recruitment",
    title: "Field Mobiliser — Source-State Recruitment",
    location: "Multi-Region (NE India, Tamil Nadu, AP, Telangana, Odisha, Jharkhand, WB, Bihar, UP, Chhattisgarh)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Operations",
    datePosted: "2026-05-24",
    summary:
      "On-the-ground recruitment officer in source districts — find, motivate, and onboard candidates from your home region for verified placements in metro cities. High-impact, field-based role with clear growth path.",
    responsibilities: [
      "Build and run a monthly mobilisation plan for your district / cluster — villages, blocks, urban wards, training institutes, SHGs, NGOs, panchayat networks, and faith-based community gatherings.",
      "Conduct field visits, group meetings, and 1:1 conversations with prospective candidates (most often women aged 21–55, but also couples for housekeeping / farmhouse / security roles).",
      "Partner with local stakeholders — Panchayat Secretaries, ASHAs, anganwadi workers, ITI placement cells, JSS, DDU-GKY and PMKVY centres, NRLM / SRLM SHG federations, church / mahila mandal groups, local agents — to generate consistent inflow of credible leads.",
      "Run small community awareness sessions about live-in, full-time, and patient-care opportunities in cities; bust myths around safety, food, and treatment; explain salary structure, weekly off, leave policy, and return travel.",
      "Conduct structured screening: age, marital status, family permission, language(s) spoken, prior work, cooking style, health, willingness to relocate, expected salary, joining timeline.",
      "Pre-qualify candidates against current city demand: live-in maid, full-time maid, cook (veg / non-veg, regional cuisine), nanny, elderly / patient care, couple housekeeping, farmhouse couple, Japa maid, etc.",
      "Set realistic expectations on salary band, working hours, food, accommodation, off-day, and city culture. Never over-promise — under-promise and let the city team close.",
      "Capture Aadhaar, PAN (where available), photograph, voter ID / ration card, two reference contacts, current and permanent address with landmark, and live geo-tagged location.",
      "Conduct basic verbal reference check with the candidate's family head or village-level reference before the file leaves your hands.",
      "Fill out the EzyHelpers helper profile in our app / CHAP system on the same day — skills, languages, prior work history, salary expectation, joining date, photographs, video introduction, category mapping.",
      "Handle family counselling — sit with parents, in-laws, husbands, and elder siblings to address concerns about safety and respect.",
      "Coordinate travel logistics with the central placement team: train / bus booking, station pickup at the destination city, contact handoff to the city team.",
      "Stay reachable to the candidate for the first 30 days of placement; resolve homesickness, salary clarification, and family communication issues before they become drop-outs.",
      "Receive daily / weekly demand briefs from the central sourcing lead and push candidate profiles into the funnel within agreed TAT (same-day or next-day).",
      "Submit Daily Work Report (DWR): villages / locations visited, meetings held, leads generated, candidates screened, profiles created, profiles confirmed, travel covered.",
      "Follow EzyHelpers' Code of Conduct strictly: no commission from candidates, no false promises of pay, no recruitment of minors, no recruitment without family consent.",
    ],
    requirements: [
      "Mother-tongue fluency in the dominant language of your assigned cluster (e.g. Assamese / Bodo, Khasi, Tamil, Telugu, Odia, Santhali / Ho / Mundari, Bengali, Bhojpuri — as relevant to your region).",
      "Working Hindi and basic English for coordination with the central team in Bangalore / Delhi.",
      "Roughly 1–4 years of field experience in any of: blue-collar recruitment, NRLM / SRLM / NGO field work, microfinance loan officer, insurance agent, ASHA / anganwadi supervisor, FMCG distribution, DDU-GKY mobiliser, skill-development counsellor, or domestic-help / placement agency field role.",
      "Strong local network — you should already know your district. People should already know you.",
      "A two-wheeler and valid driving licence, and the ability to cover 40–80 km a day on field.",
      "Smartphone literacy: WhatsApp, Google Maps, our app, photo upload, basic typing in your local language.",
      "High integrity — recruitment of vulnerable workers is a sensitive job. We do background checks on Field Mobilisers themselves.",
      "Comfort travelling 20–24 working days a month within your cluster, with occasional 2–4 day trips to the destination city.",
      "10+2 / Class 12 minimum; graduate preferred but not mandatory.",
    ],
  },
  {
    slug: "field-recruiter-business-development-executive-pan-india",
    title: "Field Recruiter / Business Development Executive — PAN India",
    location: "Field-Based (PAN India · serving Bengaluru and other locations)",
    city: "Bangalore",
    type: "Full-time",
    employmentType: "FULL_TIME",
    category: "Operations",
    datePosted: "2026-05-28",
    summary:
      "Recruit domestic helpers, caregivers, babysitters, cooks, and housekeeping staff from local cities and nearby villages. Field-based role with flexible hours, immediate joining.",
    responsibilities: [
      "Find and recruit domestic helpers and caregivers from local cities and villages.",
      "Source candidates across multiple roles: Housekeeping, Baby Care, Elderly Care, Cooking, Live-in Helpers, and Caregivers.",
      "Build partnerships with local agents, villages, training centres, and communities.",
      "Conduct helper screening and provide onboarding support.",
      "Coordinate closely with the Bengaluru operations team.",
      "Drive mobilisation and referral hiring programs.",
      "Maintain a strong pipeline of candidates through field visits and references.",
    ],
    requirements: [
      "Hindi is a must — proficiency is essential for this role.",
      "Good communication skills.",
      "Local language knowledge preferred.",
      "Comfortable with field work and local travel.",
      "Strong convincing and networking skills.",
      "Experience in recruitment, sales, field work, or manpower hiring is preferred.",
      "Freshers with strong local connections are welcome to apply.",
    ],
  },
];

export function getCareerRole(slug: string): CareerRole | undefined {
  return CAREER_ROLES.find((r) => r.slug === slug);
}
